//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WebFormsApp
{
    public partial class Default
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::EndOfDayTime.WebForms.EndOfDayTimeTextBox eodtStart;
        protected global::EndOfDayTime.WebForms.EndOfDayTimeTextBox eodtEnd;

        protected global::System.Web.UI.WebControls.Button btnSubmit;

        protected global::System.Web.UI.WebControls.Panel  pnlError;
        protected global::System.Web.UI.WebControls.Label  lblError;

        protected global::System.Web.UI.WebControls.Panel  pnlResult;
        protected global::System.Web.UI.WebControls.Label  lblResult;
    }
}