<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EndOfDayTime.Core\EndOfDayTime.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\endofdaytime-input.js">
        <LogicalName>EndOfDayTime.WebForms.endofdaytime-input.js</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
